name: Deploy (Backend + Frontend)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Magnus Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 89.249.60.4
          username: magnus
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e

            PROJECT_DIR=/var/www/backend/task-manager

            ########################################
            # 1. Kodlarni yangilash
            ########################################
            echo ">>> Git pull..."
            cd $PROJECT_DIR
            git pull origin main

            ########################################
            # 2. BACKEND (Django)
            ########################################
            echo ">>> Backend deploy..."
            cd $PROJECT_DIR/backend

            source venv/bin/activate
            pip install -r requirements.txt --quiet
            python manage.py migrate --no-input
            # python manage.py collectstatic --no-input

            sudo systemctl restart task-manager

            echo ">>> Backend tayyor!"

            ########################################
            # 3. FRONTEND (React + Vite)
            ########################################
            echo ">>> Frontend build..."
            cd $PROJECT_DIR/frontend

            npm install --silent
            npm run build

            sudo systemctl reload nginx

            echo "âœ… Deploy muvaffaqiyatli yakunlandi!"
